# Generated by Django 5.2.dev20241016095222 on 2025-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_daydateoverride_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place_override',
        ),
        migrations.AddField(
            model_name='event',
            name='place_override',
            field=models.ManyToManyField(null=True, to='api.eventplace', verbose_name='Места'),
        ),
    ]
