# Generated by Django 5.2.dev20241016095222 on 2025-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_event_place_override_event_place_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event_canceled',
            field=models.BooleanField(default=False, verbose_name='Событие отменено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_override',
            field=models.ManyToManyField(to='api.eventplace', verbose_name='Места'),
        ),
    ]
