# Generated by Django 5.2.dev20241016095222 on 2025-02-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_is_event_canceled_alter_event_place_override'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='place_override',
            new_name='places_override',
        ),
        migrations.RemoveField(
            model_name='abstractevent',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.AddField(
            model_name='abstractevent',
            name='holds_on_dates',
            field=models.DateField(null=True, verbose_name='Проводится только в заданные дни'),
        ),
        migrations.AddField(
            model_name='abstractevent',
            name='places',
            field=models.ManyToManyField(to='api.eventplace', verbose_name='Места'),
        ),
        migrations.AddField(
            model_name='abstractevent',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.schedule', verbose_name='Расписание'),
        ),
    ]
