# Generated by Django 5.2.dev20241016095222 on 2025-02-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_schedule_course_remove_schedule_faculty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='abstract_schedule',
            new_name='schedule_template',
        ),
    ]
