# Generated by Django 5.2.dev20241016095222 on 2025-03-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_abstract_schedule_schedule_schedule_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'verbose_name': 'Шаблон расписания', 'verbose_name_plural': 'Шаблоны расписаний'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.scheduletemplate', verbose_name='Шаблон расписания'),
        ),
    ]
