# Generated by Django 5.2.dev20241016095222 on 2025-04-14 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_scheduletemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractevent',
            name='holds_on_dates',
        ),
        migrations.AddField(
            model_name='abstractevent',
            name='holds_on_date',
            field=models.DateField(blank=True, null=True, verbose_name='Проводится только в заданный день'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starting_day_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.abstractday', verbose_name='Номер дня начала первого повторяющегося цикла'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='repetition_period',
            field=models.IntegerField(verbose_name='Период повторения в днях'),
        ),
    ]
