# Generated by Django 5.2.dev20241016095222 on 2025-04-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_abstractevent_holds_on_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='daydateoverride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.daydateoverride', verbose_name='Перенос дня'),
        ),
        migrations.AddField(
            model_name='event',
            name='overriden_date',
            field=models.DateField(blank=True, null=True, verbose_name='Изменённая дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата по раскладке'),
        ),
    ]
