# Generated by Django 5.2.dev20241016095222 on 2025-04-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_daydateoverride_event_overriden_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='daydateoverride',
        ),
        migrations.AddField(
            model_name='event',
            name='date_overrider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.daydateoverride', verbose_name='Перенос дня'),
        ),
    ]
