# Generated by Django 5.2.dev20241016095222 on 2025-04-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_event_daydateoverride_event_date_overrider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_overrider',
            new_name='date_override',
        ),
    ]
