# Generated by Django 5.2.dev20241016095222 on 2025-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_date_overrider_event_date_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='overriden_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
