# Generated by Django 5.2.dev20241016095222 on 2025-05-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_daydateoverride_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cancel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eventcancel', verbose_name='Отмена события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.daydateoverride', verbose_name='Перенос дня'),
        ),
    ]
